name: ecom_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0-259.0.dev


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.14.2
  lottie: ^3.3.1
  timeago: ^3.7.0
  supabase_flutter: ^2.8.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.4
  get_storage: ^2.1.1
  fl_chart: ^0.70.0
  package_info_plus: ^8.1.2
  image_picker: ^1.0.7
  http: ^1.2.1
  path: ^1.9.0
  mime: ^1.0.4
  country_state_city_pro: ^0.0.6
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  video_player: ^2.8.2
  chewie: ^1.7.5
  webview_flutter: ^4.4.2
  crypto: ^3.0.3
  url_launcher: ^6.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true

  assets:
    - assets/images/carousel/
    - assets/images/category/
    - assets/images/products/
    - assets/images/logo.png
    - assets/images/placeholder.jpg
    - assets/lottie/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
 
